package com.uc.webview.export.extension;

import com.uc.webview.base.KeyIdMap;

/* compiled from: Taobao */
/* loaded from: /Users/corson/Downloads/taobao_decompiled/build/apk/classes9.dex */
public interface SettingKeys {
    public static final int ACTIVITY_STATUS_DESTROY = 3;
    public static final int ACTIVITY_STATUS_PAUSE = 1;
    public static final int ACTIVITY_STATUS_RESUME = 2;
    public static final int ACTIVITY_STATUS_SCREEN_LOCK = 4;
    public static final int ACTIVITY_STATUS_SCREEN_UNLOCK = 5;
    public static final int ACTIVITY_STATUS_UNKNOWN = 0;
    public static final int APP_MODE_DEFAULT = 0;
    public static final int APP_MODE_TINKER_PATCH = 1;
    public static final String AXSupportServiceList;
    public static final String ActivityStatus;
    public static final String AdaptiveLayoutBlacklist;
    public static final String AdaptiveLayoutEnable;
    public static final String AllowCommitAllPerfData;
    public static final String AllowJSSetInfoList;
    public static final String AllowPopupList;
    public static final String ApolloSettings;
    public static final String AppMode;
    public static final String AudioOutputUseAAudio;
    public static final String AuthMediaJsApi;
    public static final int BACKUP_RENDER_WARMUP_STRATEGY_AFTER_MAIN_RENDER_READY = 2;
    public static final int BACKUP_RENDER_WARMUP_STRATEGY_CORE_STARTUP = 1;
    public static final int BACKUP_RENDER_WARMUP_STRATEGY_DEFAULT = -1;
    public static final int BACKUP_RENDER_WARMUP_STRATEGY_DISABLE = 0;
    public static final String BPGLibPath;
    public static final int BUSINESS_MODE_DEFAULT = 0;
    public static final int BUSINESS_MODE_SELF_BIZ = 1;
    public static final String BackupRenderWarmupStrategy;
    public static final String BlockBackgroundMediaPlay;
    public static final String BwListEmbedderWarmUpUrls;
    public static final String BwListUploadStatKeys;
    public static final int COOKIE_TYPE_HYBRID = 4;
    public static final int COOKIE_TYPE_SYSTEM = 1;
    public static final int COOKIE_TYPE_UC = 2;
    public static final int COOKIE_TYPE_UC_ENCRYPT = 3;
    public static final int CORE_FEATURE_CHROME_EXTENSION = 2;
    public static final int CORE_FEATURE_DEFAULT = 0;
    public static final int CORE_FEATURE_INSPECTOR = 4;
    public static final int CORE_FEATURE_WEBRTC = 8;
    public static final int CORE_FULL_CAPACITY = 1;
    public static final int CORE_TYPE_READY_CORE_AUTH_FAILED = 8;
    public static final int CORE_TYPE_READY_CORE_AUTH_SUCCESS = 7;
    public static final int CORE_TYPE_READY_DOWNLOAD_FALLBACK = 3;
    public static final int CORE_TYPE_READY_FORCE_SYSTEM = 6;
    public static final int CORE_TYPE_READY_INIT_FAILED = 2;
    public static final int CORE_TYPE_READY_NO_INIT_TASK = 5;
    public static final int CORE_TYPE_READY_U4 = 1;
    public static final int CORE_TYPE_READY_WAIT_TIMEOUT = 4;
    public static final String CORSV8WhiteList;
    public static final String CORSWhiteList;
    public static final String CORSWhiteListCore;
    public static final int CREATE_FLAG_BUSINESS_MODE_SELF_BIZ = 1048576;
    public static final int CREATE_FLAG_FORCE_USING_SYSTEM = 2;
    public static final int CREATE_FLAG_PAGE_BIZ_MODE_PRIVATE = 1048576;
    public static final int CREATE_FLAG_PAGE_BIZ_MODE_PUBLIC = 4194304;
    public static final int CREATE_FLAG_QUICK = 1;
    public static final int CREATE_FLAG_RENDER_STRATEGY_ONLY_VALID_ONCE = 524288;
    public static final int CREATE_FLAG_USE_BACKUP_RENDER = 1024;
    public static final int CREATE_FLAG_USE_BACKUP_RENDER_IF_READY = 2048;
    public static final int CREATE_FLAG_USE_ISOLATE_RENDER = 4096;
    public static final int CREATE_FLAG_USE_NORMAL_RENDER = 8192;
    public static final int CRX_MANAGER_SUPPORT_INSTALL_EXTENSION_BY_URL = 0;
    public static final String CachePageFreeFirstThanKeep;
    public static final String CachePageNumber;
    public static final String CachePageNumberOnCritical;
    public static final String CachePageNumberOnModerate;
    public static final String CaptureEnableWaitLoad;
    public static final String ChromeExtensionInstallMapping;
    public static final String ChromeExtensionsAccessDenyUrlList;
    public static final String ChromeExtensionsAccessPartialDenyUrlList;
    public static final String ChromeExtensionsBlackList;
    public static final String ChromeExtensionsEnabled;
    public static final String ChromeExtensionsMV2AutoReload;
    public static final String ChromeExtensionsSelfBizUrlList;
    public static final String ChromeExtensionsWhiteList;
    public static final String CommonLibDir;
    public static final String CommonLibParsName;
    public static final String ConsoleUndefStatsEnabled;
    public static final String CookiesBlacklistForJs;
    public static final String CoreDexPath;
    public static final String CoreLibPath;
    public static final String CoreOdexPath;
    public static final String CpnDownloadCrest;
    public static final String CpnTaskDelayTime;
    public static final String CrxAddDefaultViewportOnPopupPage;
    public static final String CrxForceMediaResourceSniffing;
    public static final String CrxStatsEnabled;
    public static final String CustomAttributesControlType;
    public static final String CustomFont;
    public static final String DecodeFailIsOn;
    public static final String DisableAAudio;
    public static final String DisableAlivePlayerLimit;
    public static final String DisableAutoplayMACList;
    public static final String DisableAutoplayMANList;
    public static final String DisableBFCache;
    public static final String DisableExitFullscreenWhenJsPrompt;
    public static final String DisableExtendViewFloat;
    public static final String DisableExtendViewTitles;
    public static final String DisableImageView;
    public static final String DisableJsFullscreenWhenHybrid;
    public static final String DisableMSEAdaptiveList;
    public static final String DisableShowNativeCtrlWhenLoading;
    public static final String DiscardableDataKeepSecond;
    public static final String DiscardableLimitBytes;
    public static final String DiscardableReleaseFreeAfterSecond;
    public static final String DiscardableReleaseFreeAfterTimeSwitch;
    public static final String DiscardableReleaseFreeUntilByte;
    public static final String DispatchClickEventToJsList;
    public static final String DistinguishJSError;
    public static final String EmbedViewEmbedSurfaceEnableList;
    public static final String EmbedViewHybridRenderEnableList;
    public static final String EmbedViewReattachList;
    public static final String EmbedViewStatsEnable;
    public static final String EmbedViewSurfaceDetectConfig;
    public static final String EmbedViewTransparentTypeList;
    public static final String EmbedderBuildTimestamp;
    public static final String EnableBeforePlayCallbackList;
    public static final String EnableBelowFloatingWindow;
    public static final String EnableBindPerformanceCore;
    public static final String EnableBlockNavigation;
    public static final String EnableCustomFont;
    public static final String EnableDebugging;
    public static final String EnableFDSanitizer;
    public static final String EnableFileEmptyScreenCheck;
    public static final String EnableFitScreenTextWrap;
    public static final String EnableGPUProcessOnLowEndDevice;
    public static final String EnableGetCacheFileList;
    public static final String EnableHittestPrefetch;
    public static final String EnableHttpCacheWhileUsingNetworkHosting;
    public static final String EnableInRendererGpu;
    public static final String EnableKLog;
    public static final String EnableKeywordHyperlink;
    public static final String EnableKeywordHyperlinkStat;
    public static final String EnableLottie;
    public static final String EnableLottieStatsUrl;
    public static final String EnableLowLatencyCompat;
    public static final String EnableMSEAdaptive;
    public static final String EnableMSEUseHybrid;
    public static final String EnableNetworkBrotli;
    public static final String EnableNetworkHosting;
    public static final String EnableNetworkHostingDisbaleDataInflated;
    public static final String EnablePerformanceMarkTiming;
    public static final String EnablePreloadVideoBasedResponseHeader;
    public static final String EnablePreloadVideoSourceList;
    public static final String EnableRunInSeperateThread;
    public static final String EnableSameSiteCookieDegradation;
    public static final String EnableShouldInterceptRequest;
    public static final String EnableSnapshotBackgroundDeserialize;
    public static final String EnableSnapshotEnabledByURL;
    public static final String EnableSnapshotScriptResourceCache;
    public static final String EnableTimingTTI;
    public static final String EnableV8ContextSnapshot;
    public static final String EnableVideoSuperToolbar;
    public static final String EnableVideoViewUnderWebView;
    public static final String EnableWebViewListenerStandardization;
    public static final String EnableWebrtcH265;
    public static final String EnableWebviewEventEmptyScreen;
    public static final String ExtImgDecoderOn;
    public static final String ExtendViewAutoFloatMinDuration;
    public static final String FFMpegAudioDecoderSoPaths;
    public static final String FeatureStatsEnabled;
    public static final String FitScreenTextWrapBlacklist;
    public static final String FocusAutoPopupInputWhitelist;
    public static final String ForceEnableUserSelect;
    public static final int GPU_PROCESS_DEFAULT = -1;
    public static final int GPU_PROCESS_FULL = 2;
    public static final int GPU_PROCESS_IN_PROCESS = 1;
    public static final int GPU_PROCESS_SINGLE = 0;
    public static final int GPU_PROC_GONE_INFO_TYPE_CRASHED = 1;
    public static final int GPU_PROC_GONE_INFO_TYPE_HAS_WEBGL = 2;
    public static final int GPU_PROC_GONE_INFO_TYPE_WEBGLCONTEXTLOST_HAD_SET = 4;
    public static final int GPU_PROC_GONE_INFO_TYPE_WEBGLCONTEXTRESTORED_HAD_SET = 8;
    public static final String GlobalDefaultUserAgent;
    public static final String GlobalWebviewUA;
    public static final String GpuProcMode;
    public static final String GrDiscardableLimitByte;
    public static final String GrDiscardableLowEndLimitByte;
    public static final String GrResourceCacheLimitByte;
    public static final String GrResourceCacheLowEndLimitByte;
    public static final String GwpAsanConfig;
    public static final String H264EncoderType;
    public static final String HideUcwebBlackList;
    public static final String HybridCoveredCheckBlockList;
    public static final String HybridCoveredCheckType;
    public static final int INIT_STATUS_CORE_SO_PRELOADING = 16;
    public static final int INIT_STATUS_DEX_READY = 128;
    public static final int INIT_STATUS_DEX_VERIFIED = 64;
    public static final int INIT_STATUS_ENGINE_INITED = 2048;
    public static final int INIT_STATUS_ENGINE_STARTING = 2;
    public static final int INIT_STATUS_FAILED = 8192;
    public static final int INIT_STATUS_FIRST_U4_WEBVIEW = 16384;
    public static final int INIT_STATUS_FIRST_WEBVIEW_CREATING = 4;
    public static final int INIT_STATUS_LIB_VERIFIED = 1024;
    public static final int INIT_STATUS_MAX_BIT = 14;
    public static final int INIT_STATUS_NATIVE_INTIALIZING = 1;
    public static final int INIT_STATUS_NONE = 0;
    public static final int INIT_STATUS_SCLF_ASYN = 512;
    public static final int INIT_STATUS_SCLF_SYNC = 256;
    public static final int INIT_STATUS_STARTED = 32;
    public static final int INIT_STATUS_SUCCESS = 4096;
    public static final int INIT_STATUS_URL_LOADING = 8;
    public static final int ISOLATE_RENDER_WARMUP_STRATEGY_AFTER_FIRST_PAGE_FINISHED = 4;
    public static final int ISOLATE_RENDER_WARMUP_STRATEGY_AFTER_FIRST_RENDER_READY = 3;
    public static final int ISOLATE_RENDER_WARMUP_STRATEGY_CORE_STARTUP = 1;
    public static final int ISOLATE_RENDER_WARMUP_STRATEGY_DEFAULT = -1;
    public static final int ISOLATE_RENDER_WARMUP_STRATEGY_DISABLE = 0;
    public static final String IgnoreSeekToEnd;
    public static final String IgnoreTouchOnFloatingWin;
    public static final String IgnoreViewportMetaList;
    public static final String InjectInHeadJavaScript;
    public static final String InjectInHeadJavaScriptUrl;
    public static final String InjectJSInHeadHostList;
    public static final String IsHardwareAC;
    public static final String IsInternationalVersion;
    public static final String IsRunningInWebViewSdk;
    public static final String IsolateRenderWarmupStrategy;
    public static final String JsEvalVerboseBacktrace;
    public static final String JsapiAsyncFunctionList;
    public static final String KeywordHyperlinkBlacklist;
    public static final String KeywordHyperlinkChannelDistribution;
    public static final String KeywordHyperlinkCount;
    public static final String KeywordHyperlinkInterval;
    public static final String KeywordHyperlinkLength;
    public static final String KeywordHyperlinkSensitiveWords;
    public static final int LIB_DIGEST_TYPE_MD5 = 2;
    public static final int LIB_DIGEST_TYPE_SHA1 = 3;
    public static final int LIB_DIGEST_TYPE_SHA256 = 4;
    public static final int LIB_VERIFY_POLICY_FULL = 2;
    public static final int LIB_VERIFY_POLICY_NONE = 0;
    public static final int LIB_VERIFY_POLICY_QUICK = 1;
    public static final String LastUserInputTime;
    public static final String LocalDisableExtendViewFloat;
    public static final String LocalEnableMSE;
    public static final String LongPressTimeout;
    public static final String MSEHybridWhiteList;
    public static final String MSEListType;
    public static final String MaxDomTreeDepth;
    public static final String MaxWebWorkerCountForBFCache;
    public static final String MediaCodecType;
    public static final String MediaDisableFloatingWindow;
    public static final String MediaEnableAutoPlayList;
    public static final String MediaPlayerLimits;
    public static final String MediaPlayerPlugin;
    public static final int NAVIGATION_TYPE_ANCHOR_CLICK = 3;
    public static final int NAVIGATION_TYPE_EXT_REFRESH = 5;
    public static final int NAVIGATION_TYPE_LOCATION_RELOAD = 4;
    public static final int NAVIGATION_TYPE_META_REFRESH = 2;
    public static final int NAVIGATION_TYPE_WINDOW_LOCATION = 0;
    public static final int NAVIGATION_TYPE_WINDOW_OPEN = 1;
    public static final String NetworkHostingRetry;
    public static final String NetworkHostingRetryCr;
    public static final String NetworkHostingServiceInstance;
    public static final String NetworkHostingUnSupportHostList;
    public static final String NetworkHostingUnSupportMethod;
    public static final String NonHybridForMutedAndNoControls;
    public static final String NonInternalBussinessBids;
    public static final String OpenCacheLog;
    public static final int PAGE_BIZ_MODE_DEFAULT = 0;
    public static final int PAGE_BIZ_MODE_PRIVATE = 1;
    public static final int PAGE_BIZ_MODE_PUBLIC = 2;
    public static final int PAGE_BIZ_MODE_SCOPE_CURRENT = 0;
    public static final int PAGE_BIZ_MODE_SCOPE_NEXT_LOADING = 1;
    public static final int PAGE_BIZ_MODE_SPLV = 4;
    public static final String PageEnableAdBlock;
    public static final String PageEnableForceDefaultVLinkColor;
    public static final String PageFormSave;
    public static final String PageImageLinkUnderlineType;
    public static final String PageLayoutStyle;
    public static final String PasswordFillPromptOnLoad;
    public static final String PinchZoomStatsEnable;
    public static final String PrerenderPendingLoadEvent;
    public static final String PrivateDataDirSuffix;
    public static final int RELOAD_TYPE_INVALID = -1;
    public static final int RELOAD_TYPE_JS = 8;
    public static final int RELOAD_TYPE_NONE = 0;
    public static final int RELOAD_TYPE_PROCESS_GONE_CORE = 4;
    public static final int RELOAD_TYPE_PROCESS_GONE_SHELL = 2;
    public static final int RELOAD_TYPE_SHELL = 1;
    public static final int RELOAD_TYPE_V8_SNAPSHOT = 16;
    public static final int RENDER_PIPELINE_TYPE_DEFAULT = 0;
    public static final int RENDER_PIPELINE_TYPE_DIRECT = 2;
    public static final int RENDER_PIPELINE_TYPE_SYNC = 1;
    public static final int RENDER_PROCESS_DEFAULT = -1;
    public static final int RENDER_PROCESS_DISABLE = 0;
    public static final int RENDER_PROCESS_ISOLATE = 2;
    public static final int RENDER_PROCESS_ISOLATE_WITHOUT_SECCOMP = 12;
    public static final int RENDER_PROCESS_NORMAL = 1;
    public static final int RENDER_PROCESS_NORMAL_WITH_SECCOMP = 11;
    public static final int RENDER_PROC_STRATEGY_DEFAULT = 0;
    public static final int RENDER_PROC_STRATEGY_USE_BACKUP_RENDER = 2;
    public static final int RENDER_PROC_STRATEGY_USE_BACKUP_RENDER_IF_READY = 3;
    public static final int RENDER_PROC_STRATEGY_USE_ISOLATE = 256;
    public static final int RENDER_PROC_STRATEGY_USE_MAIN_RENDER = 1;
    public static final int RENDER_PROC_STRATEGY_USE_NORMAL = 512;
    public static final String React16URLs;
    public static final String React17URLs;
    public static final String React18URLs;
    public static final String RecordIsNoFootmark;
    public static final String ReloadIfUAChanged;
    public static final String RemoveImageFromCache;
    public static final String RenderPipelineType;
    public static final String RenderProcMode;
    public static final String ResourceBlockRequestRuleList;
    public static final int SDK_PATCH_MODE_DISABLE = 0;
    public static final int SDK_PATCH_MODE_DOWNLOAD_BASE = 1;
    public static final int SDK_PATCH_MODE_ENABLE = 2;
    public static final int SDK_PATCH_MODE_USE_DEBUG_CORE = 3;
    public static final int STAT_OPTIONS_BIZ_COMMIT_PRERENDER = 8;
    public static final int STAT_OPTIONS_BIZ_IS_PRERENDERING = 4;
    public static final int STAT_OPTIONS_BIZ_NORMAL_LOADING = 16;
    public static final int STAT_OPTIONS_FIX_START = 32;
    public static final int STAT_OPTIONS_FIX_T1 = 1;
    public static final int STAT_OPTIONS_FIX_URL = 2;
    public static final int STAT_OPTIONS_NONE = 0;
    public static final int SWITCH_CORE_POLICY_NO_UPGRADE = 4;
    public static final int SWITCH_CORE_POLICY_UPGRADE = 2;
    public static final String SdkAuthExpiredTime;
    public static final String SdkAuthMaxDayRetryCount;
    public static final String SdkAuthMaxRetryCount;
    public static final String SdkAuthMaxSessionRetryCount;
    public static final String SdkAuthProductId;
    public static final String SdkCurrentAuthReqCnt;
    public static final String SdkDisableSysApiLevelsLimit;
    public static final String SdkEmbedderStartTimeStamp;
    public static final String SdkEnableCoreDexVrErrOptFor12;
    public static final String SdkEnableCorruptionDetector;
    public static final String SdkEnableDlClassLoader;
    public static final String SdkEnableLoadCoreRawDex;
    public static final String SdkEnableLogToCrashCachedInfo;
    public static final String SdkEnableLogToLogCat;
    public static final String SdkEnablePldCkMgr;
    public static final String SdkEnablePreStartCoreEngine;
    public static final String SdkEnablePreStartCoreEngineAsync;
    public static final String SdkEnableReportInitFailedLog;
    public static final String SdkEnableReportWebViewInvalidThread;
    public static final String SdkEnableReuseAndSameCoreNotReExtract;
    public static final String SdkEnableReuseLastCore;
    public static final String SdkEnableSdcardPermissionCheck;
    public static final String SdkEnableStats;
    public static final String SdkEnableUVSampling;
    public static final String SdkEnableUseTempDirToExtract;
    public static final String SdkEnableWebviewWarmup;
    public static final String SdkEnabledAbiX86Detector;
    public static final String SdkExtractCountWhileInitFailed;
    public static final String SdkFullCapacityCoreBlackList;
    public static final String SdkHttpConnReadTimeOut;
    public static final String SdkHttpConnTimeOut;
    public static final String SdkInitFailedAndFallbackSystem;
    public static final String SdkInitWebViewMaxWaitMillis;
    public static final String SdkInitWithCpuSched;
    public static final String SdkLibVerifyPolicy;
    public static final String SdkNativeLibDigestType;
    public static final String SdkPatchMode;
    public static final String SdkPatchNUCtrlDays;
    public static final String SdkPostInitNewCoreDelayMillis;
    public static final String SdkReuseLastCoreVersionSpan;
    public static final String SdkStatsInlandServer;
    public static final String SdkStatsInterServer;
    public static final String SdkStatsUploadCrazyTime;
    public static final String SdkStatsUploadInterval;
    public static final String SdkSysApiLevelsLimitList;
    public static final String SdkUseUCPlayer;
    public static final String SdkUsingDebugingCore;
    public static final String SelectPopupTopMargin;
    public static final String SendDecodeFailWebviewEvent;
    public static final String ShouldInterceptRequestTimeoutLimit;
    public static final String ShowMediaExtendViewType;
    public static final String ShowNativeCtrlWhenLoadingType;
    public static final String T1T3DetailSampleRate;
    public static final String T2FinishTimeout;
    public static final String T2StatRenderProcessBound;
    public static final String T2StatRenderProcessConnected;
    public static final String TempKuyingCheckWithPort;
    public static final String ThreadWatchdogAlarmDuration;
    public static final String ThreadWatchdogDumpJSRate;
    public static final String ThreadWatchdogDumpNativeRate;
    public static final String ThreadWatchdogWatchList;
    public static final String U4StateLineSwitch;
    public static final String UBISiLang;
    public static final String UBISiVersion;
    public static final String UBISn;
    public static final String UBIUtdId;
    public static final String UCCookieType;
    public static final String UIIsNightMode;
    public static final String UndefineStatsEnabled;
    public static final String V8CodeCacheThresholdMB;
    public static final String V8SnapshotHeaderVersion;
    public static final int VERIFY_CORE_CONTENT_INVALID = 5;
    public static final int VERIFY_CORE_EXCEPTION = 7;
    public static final int VERIFY_CORE_FILE_INVALID = 1;
    public static final int VERIFY_CORE_INVALID_CORE_DEX = 8;
    public static final int VERIFY_CORE_LIBRARIES_INVALID = 3;
    public static final int VERIFY_CORE_LIBRARIES_MISSING = 2;
    public static final int VERIFY_CORE_NO_LIBINFO = 6;
    public static final int VERIFY_CORE_OK = 0;
    public static final int VERIFY_CORE_SIZE_INVALID = 4;
    public static final String VideoCustomAttributesWhiteList;
    public static final String VideoDisableMSE;
    public static final String VideoDisableMetaAutoPlay;
    public static final String VideoDisablePopstate;
    public static final String VideoEnableAutoLandscape;
    public static final String VideoEnableMSE;
    public static final String VideoEnablePreciseSeek;
    public static final String VideoEnableUploadStats;
    public static final String VideoIgnoreFirstPos;
    public static final String VideoIgnorePlayWhenVisible;
    public static final String VideoMSEWhiteList;
    public static final String VideoUseStandardMode;
    public static final String VideoUseStandardModeList;
    public static final String VideoUseSurfaceView;
    public static final String VisibilityChangeEventDisable;
    public static final int WEBVIEW_EVENT_TYPE_ADBLOCK_CSS_RULE_MATCHED = 201;
    public static final int WEBVIEW_EVENT_TYPE_AUDIO_DATA_USED = 105;
    public static final int WEBVIEW_EVENT_TYPE_BASE_COLOR_EMPTY_SCREEN = 16;
    public static final int WEBVIEW_EVENT_TYPE_BEFORE_NAVIGATION = 25;
    public static final int WEBVIEW_EVENT_TYPE_BLOCK_WINDOW = 0;
    public static final int WEBVIEW_EVENT_TYPE_COMMIT_PRERENDER = 31;
    public static final int WEBVIEW_EVENT_TYPE_DETACHED_FROM_WINDOW = 24;
    public static final int WEBVIEW_EVENT_TYPE_EMPTY_SCREEN = 9;
    public static final int WEBVIEW_EVENT_TYPE_EMPTY_SCREEN_INFO = 15;
    public static final int WEBVIEW_EVENT_TYPE_FIRST_LAYOUT_FINISHED = 27;
    public static final int WEBVIEW_EVENT_TYPE_FIRST_PAINT = 17;
    public static final int WEBVIEW_EVENT_TYPE_GETJS_URL = 22;
    public static final int WEBVIEW_EVENT_TYPE_HIDE_SOFTKEYBOARD = 1;
    public static final int WEBVIEW_EVENT_TYPE_HITTEST_RESULT = 28;
    public static final int WEBVIEW_EVENT_TYPE_LINKID_NOTIFICATION = 20;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_OTHER_TRIGGER = 11;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_STATUS_START = 4;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_STATUS_T0 = 5;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_STATUS_T1 = 6;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_STATUS_T2 = 7;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_STATUS_T2_PAINT = 13;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_STATUS_T2_TRACE = 14;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_STATUS_T3 = 8;
    public static final int WEBVIEW_EVENT_TYPE_LOADING_USER_TRIGGER = 10;
    public static final int WEBVIEW_EVENT_TYPE_MEDIA_MESSAGE_STATS = 103;
    public static final int WEBVIEW_EVENT_TYPE_MULTI_COLOR_EMPTY_SCREEN = 23;
    public static final int WEBVIEW_EVENT_TYPE_NETWORK_IP_RESOLVED = 12;
    public static final int WEBVIEW_EVENT_TYPE_NO_MATCH_IMG_DECODER = 21;
    public static final int WEBVIEW_EVENT_TYPE_ON_GPU_PROCESS_READY = 110;
    public static final int WEBVIEW_EVENT_TYPE_ON_RENDER_PROCESS_READY = 107;
    public static final int WEBVIEW_EVENT_TYPE_PAGE_STARTED_EX = 26;
    public static final int WEBVIEW_EVENT_TYPE_SHARE_VIDEO = 2;
    public static final int WEBVIEW_EVENT_TYPE_SHOW_VIDEO_GESTURE_GUIDE = 3;
    public static final int WEBVIEW_EVENT_TYPE_VIDEO_DATA_USED = 104;
    public static final int WEBVIEW_EVENT_TYPE_VIDEO_ENTER_FULLSCREEN = 101;
    public static final int WEBVIEW_EVENT_TYPE_VIDEO_EXIT_FULLSCREEN = 102;
    public static final int WEBVIEW_EVENT_TYPE_WEBGLCONTEXT_EVENT_LISTENER_COUNT_CHANGED = 111;
    public static final int WEBVIEW_EVENT_TYPE_WEBGL_ERROR_STATE = 19;
    public static final int WEBVIEW_EVENT_TYPE_WEBGL_JS_ERROR = 18;
    public static final int WEBVIEW_EVENT_TYPE_WEB_PAGE_USES_WEBGL = 106;
    public static final int WEBVIEW_MULTI_PROCESS_DEFAULT = -1;
    public static final int WEBVIEW_MULTI_PROCESS_ISOLATE = 2;
    public static final int WEBVIEW_MULTI_PROCESS_NORMAL = 1;
    public static final int WEBVIEW_MULTI_PROCESS_SINGLE = 0;
    public static final String WPKStatPV;
    public static final String WPKStatSampleRate;
    public static final String WebAudioUserGestureRequired;
    public static final String XhrSyncTimeoutLimit;

    static {
        String[] strArr = KeyIdMap.f14251a;
        CoreDexPath = strArr[174];
        CoreLibPath = strArr[175];
        CoreOdexPath = strArr[176];
        CommonLibParsName = strArr[172];
        CustomFont = strArr[1];
        DisableBFCache = strArr[2];
        DistinguishJSError = strArr[4];
        GwpAsanConfig = strArr[179];
        OpenCacheLog = strArr[14];
        ThreadWatchdogWatchList = strArr[190];
        ThreadWatchdogAlarmDuration = strArr[187];
        ThreadWatchdogDumpJSRate = strArr[188];
        ThreadWatchdogDumpNativeRate = strArr[189];
        IsHardwareAC = strArr[10];
        AppMode = strArr[111];
        RenderProcMode = strArr[131];
        BackupRenderWarmupStrategy = strArr[112];
        IsolateRenderWarmupStrategy = strArr[126];
        GpuProcMode = strArr[121];
        PrivateDataDirSuffix = strArr[211];
        CachePageNumber = strArr[113];
        CachePageNumberOnModerate = strArr[115];
        CachePageNumberOnCritical = strArr[114];
        CachePageFreeFirstThanKeep = strArr[0];
        CaptureEnableWaitLoad = strArr[21];
        CookiesBlacklistForJs = strArr[173];
        RenderPipelineType = strArr[130];
        DisableImageView = strArr[30];
        EnableLowLatencyCompat = strArr[53];
        EnableNetworkHosting = strArr[23];
        NetworkHostingServiceInstance = strArr[210];
        WebAudioUserGestureRequired = strArr[109];
        EnableHttpCacheWhileUsingNetworkHosting = strArr[47];
        EnableWebrtcH265 = strArr[64];
        H264EncoderType = strArr[138];
        NetworkHostingUnSupportMethod = strArr[195];
        NetworkHostingUnSupportHostList = strArr[236];
        NetworkHostingRetry = strArr[194];
        NetworkHostingRetryCr = strArr[193];
        EnableNetworkHostingDisbaleDataInflated = strArr[24];
        EnableNetworkBrotli = strArr[22];
        EnableSameSiteCookieDegradation = strArr[8];
        FFMpegAudioDecoderSoPaths = strArr[198];
        EmbedViewHybridRenderEnableList = strArr[240];
        EmbedViewReattachList = strArr[241];
        EmbedViewEmbedSurfaceEnableList = strArr[239];
        EmbedViewStatsEnable = strArr[25];
        EmbedViewSurfaceDetectConfig = strArr[200];
        ForceEnableUserSelect = strArr[9];
        SelectPopupTopMargin = strArr[147];
        HideUcwebBlackList = strArr[232];
        InjectJSInHeadHostList = strArr[237];
        IgnoreTouchOnFloatingWin = strArr[68];
        InjectInHeadJavaScript = strArr[196];
        InjectInHeadJavaScriptUrl = strArr[197];
        IsRunningInWebViewSdk = strArr[13];
        ReloadIfUAChanged = strArr[15];
        GlobalWebviewUA = strArr[178];
        JsapiAsyncFunctionList = strArr[257];
        MediaPlayerPlugin = strArr[199];
        PageEnableForceDefaultVLinkColor = strArr[6];
        PageFormSave = strArr[120];
        PageImageLinkUnderlineType = strArr[128];
        PageLayoutStyle = strArr[127];
        AdaptiveLayoutEnable = strArr[16];
        AdaptiveLayoutBlacklist = strArr[227];
        EnableFitScreenTextWrap = strArr[44];
        FitScreenTextWrapBlacklist = strArr[254];
        EnableFileEmptyScreenCheck = strArr[43];
        PinchZoomStatsEnable = strArr[71];
        GlobalDefaultUserAgent = strArr[177];
        UBISiVersion = strArr[181];
        UBISn = strArr[182];
        UBISiLang = strArr[180];
        BwListEmbedderWarmUpUrls = strArr[230];
        BwListUploadStatKeys = strArr[231];
        UBIUtdId = strArr[183];
        UCCookieType = strArr[132];
        UIIsNightMode = strArr[11];
        U4StateLineSwitch = strArr[226];
        WPKStatSampleRate = strArr[169];
        WPKStatPV = strArr[110];
        EnableKeywordHyperlink = strArr[48];
        EnableKeywordHyperlinkStat = strArr[49];
        KeywordHyperlinkCount = strArr[140];
        KeywordHyperlinkInterval = strArr[141];
        KeywordHyperlinkLength = strArr[142];
        KeywordHyperlinkChannelDistribution = strArr[206];
        KeywordHyperlinkSensitiveWords = strArr[207];
        KeywordHyperlinkBlacklist = strArr[258];
        EnableKLog = strArr[50];
        T2StatRenderProcessBound = strArr[215];
        T2StatRenderProcessConnected = strArr[216];
        SdkCurrentAuthReqCnt = strArr[154];
        SdkAuthProductId = strArr[218];
        SdkAuthExpiredTime = strArr[217];
        SdkAuthMaxSessionRetryCount = strArr[155];
        SdkAuthMaxDayRetryCount = strArr[153];
        SdkAuthMaxRetryCount = strArr[156];
        SdkEnableLogToLogCat = strArr[84];
        SdkEnableReuseLastCore = strArr[88];
        SdkReuseLastCoreVersionSpan = strArr[164];
        SdkEnablePreStartCoreEngine = strArr[86];
        SdkEnablePreStartCoreEngineAsync = strArr[87];
        SdkEnableWebviewWarmup = strArr[91];
        SdkEnableSdcardPermissionCheck = strArr[90];
        SdkEnableReuseAndSameCoreNotReExtract = strArr[89];
        SdkEnablePldCkMgr = strArr[97];
        SdkEnableDlClassLoader = strArr[79];
        SdkEnableLoadCoreRawDex = strArr[81];
        SdkEnableCoreDexVrErrOptFor12 = strArr[78];
        T1T3DetailSampleRate = strArr[151];
        SdkPostInitNewCoreDelayMillis = strArr[163];
        CpnDownloadCrest = strArr[191];
        CpnTaskDelayTime = strArr[134];
        SdkPatchMode = strArr[162];
        SdkPatchNUCtrlDays = strArr[135];
        SdkFullCapacityCoreBlackList = strArr[264];
        SdkEnableCorruptionDetector = strArr[85];
        SdkEnableLogToCrashCachedInfo = strArr[83];
        IsInternationalVersion = strArr[96];
        SdkEnableStats = strArr[77];
        SdkEnableUVSampling = strArr[98];
        SdkStatsInlandServer = strArr[223];
        SdkStatsInterServer = strArr[222];
        SdkExtractCountWhileInitFailed = strArr[157];
        SdkEnableUseTempDirToExtract = strArr[93];
        SdkEnableReportInitFailedLog = strArr[80];
        SdkStatsUploadInterval = strArr[165];
        SdkStatsUploadCrazyTime = strArr[224];
        EnableWebViewListenerStandardization = strArr[101];
        SdkHttpConnTimeOut = strArr[159];
        SdkHttpConnReadTimeOut = strArr[158];
        SdkSysApiLevelsLimitList = strArr[221];
        SdkDisableSysApiLevelsLimit = strArr[76];
        SdkEnableReportWebViewInvalidThread = strArr[82];
        EmbedViewTransparentTypeList = strArr[201];
        EmbedderBuildTimestamp = strArr[219];
        SdkLibVerifyPolicy = strArr[166];
        SdkUsingDebugingCore = strArr[99];
        SdkInitWebViewMaxWaitMillis = strArr[160];
        SdkInitFailedAndFallbackSystem = strArr[95];
        SdkEnabledAbiX86Detector = strArr[92];
        SdkNativeLibDigestType = strArr[161];
        SdkEmbedderStartTimeStamp = strArr[220];
        SdkUseUCPlayer = strArr[100];
        FocusAutoPopupInputWhitelist = strArr[263];
        LongPressTimeout = strArr[143];
        CORSWhiteList = strArr[234];
        CORSWhiteListCore = strArr[235];
        CORSV8WhiteList = strArr[233];
        RecordIsNoFootmark = strArr[12];
        ResourceBlockRequestRuleList = strArr[192];
        EnableLottie = strArr[51];
        EnableLottieStatsUrl = strArr[52];
        AudioOutputUseAAudio = strArr[18];
        DisableAAudio = strArr[33];
        AuthMediaJsApi = strArr[19];
        NonHybridForMutedAndNoControls = strArr[69];
        ApolloSettings = strArr[184];
        BlockBackgroundMediaPlay = strArr[20];
        NonInternalBussinessBids = strArr[262];
        CustomAttributesControlType = strArr[136];
        DispatchClickEventToJsList = strArr[238];
        DisableAlivePlayerLimit = strArr[244];
        DisableAutoplayMANList = strArr[246];
        DisableAutoplayMACList = strArr[245];
        DisableShowNativeCtrlWhenLoading = strArr[248];
        DisableJsFullscreenWhenHybrid = strArr[35];
        EnableBeforePlayCallbackList = strArr[249];
        EnableGetCacheFileList = strArr[250];
        EnablePreloadVideoBasedResponseHeader = strArr[251];
        EnableRunInSeperateThread = strArr[56];
        EnableVideoSuperToolbar = strArr[253];
        EnableVideoViewUnderWebView = strArr[268];
        IgnoreSeekToEnd = strArr[275];
        MediaCodecType = strArr[129];
        VideoCustomAttributesWhiteList = strArr[269];
        MediaDisableFloatingWindow = strArr[270];
        EnableBelowFloatingWindow = strArr[105];
        DisableExtendViewTitles = strArr[225];
        DisableExtendViewFloat = strArr[271];
        DisableExitFullscreenWhenJsPrompt = strArr[34];
        HybridCoveredCheckType = strArr[139];
        HybridCoveredCheckBlockList = strArr[255];
        LocalDisableExtendViewFloat = strArr[260];
        ExtendViewAutoFloatMinDuration = strArr[137];
        MediaPlayerLimits = strArr[209];
        MediaEnableAutoPlayList = strArr[276];
        ShowMediaExtendViewType = strArr[149];
        ShowNativeCtrlWhenLoadingType = strArr[150];
        JsEvalVerboseBacktrace = strArr[102];
        VideoEnablePreciseSeek = strArr[273];
        VideoEnableMSE = strArr[106];
        VideoDisableMSE = strArr[272];
        VideoDisableMetaAutoPlay = strArr[103];
        VideoMSEWhiteList = strArr[265];
        EnableMSEUseHybrid = strArr[54];
        MSEHybridWhiteList = strArr[261];
        LocalEnableMSE = strArr[259];
        EnableMSEAdaptive = strArr[66];
        EnablePreloadVideoSourceList = strArr[252];
        DisableMSEAdaptiveList = strArr[247];
        MSEListType = strArr[146];
        VideoDisablePopstate = strArr[277];
        TempKuyingCheckWithPort = strArr[75];
        VideoEnableAutoLandscape = strArr[104];
        VideoEnableUploadStats = strArr[267];
        VideoIgnoreFirstPos = strArr[274];
        VideoIgnorePlayWhenVisible = strArr[108];
        VideoUseStandardMode = strArr[107];
        VideoUseStandardModeList = strArr[266];
        VideoUseSurfaceView = strArr[278];
        VisibilityChangeEventDisable = strArr[279];
        PageEnableAdBlock = strArr[5];
        AllowPopupList = strArr[229];
        ExtImgDecoderOn = strArr[67];
        RemoveImageFromCache = strArr[73];
        DecodeFailIsOn = strArr[32];
        ActivityStatus = strArr[133];
        EnableTimingTTI = strArr[61];
        EnableV8ContextSnapshot = strArr[63];
        EnableSnapshotBackgroundDeserialize = strArr[58];
        EnableSnapshotScriptResourceCache = strArr[60];
        V8SnapshotHeaderVersion = strArr[168];
        React16URLs = strArr[212];
        React17URLs = strArr[213];
        React18URLs = strArr[214];
        EnableSnapshotEnabledByURL = strArr[59];
        LastUserInputTime = strArr[208];
        BPGLibPath = strArr[186];
        MaxDomTreeDepth = strArr[144];
        DiscardableReleaseFreeAfterTimeSwitch = strArr[3];
        DiscardableLimitBytes = strArr[117];
        DiscardableReleaseFreeAfterSecond = strArr[118];
        DiscardableReleaseFreeUntilByte = strArr[119];
        DiscardableDataKeepSecond = strArr[116];
        PrerenderPendingLoadEvent = strArr[72];
        EnableBlockNavigation = strArr[37];
        AllowJSSetInfoList = strArr[228];
        AllowCommitAllPerfData = strArr[17];
        EnablePerformanceMarkTiming = strArr[55];
        EnableCustomFont = strArr[31];
        GrDiscardableLimitByte = strArr[122];
        GrDiscardableLowEndLimitByte = strArr[123];
        GrResourceCacheLimitByte = strArr[124];
        GrResourceCacheLowEndLimitByte = strArr[125];
        AXSupportServiceList = strArr[185];
        EnableFDSanitizer = strArr[41];
        EnableDebugging = strArr[40];
        FeatureStatsEnabled = strArr[42];
        UndefineStatsEnabled = strArr[62];
        ConsoleUndefStatsEnabled = strArr[38];
        XhrSyncTimeoutLimit = strArr[170];
        EnableShouldInterceptRequest = strArr[57];
        ShouldInterceptRequestTimeoutLimit = strArr[148];
        T2FinishTimeout = strArr[152];
        EnableGPUProcessOnLowEndDevice = strArr[45];
        PasswordFillPromptOnLoad = strArr[70];
        MaxWebWorkerCountForBFCache = strArr[145];
        EnableHittestPrefetch = strArr[46];
        EnableWebviewEventEmptyScreen = strArr[65];
        SendDecodeFailWebviewEvent = strArr[74];
        V8CodeCacheThresholdMB = strArr[167];
        EnableInRendererGpu = strArr[7];
        SdkInitWithCpuSched = strArr[94];
        ChromeExtensionsSelfBizUrlList = strArr[205];
        ChromeExtensionsAccessDenyUrlList = strArr[202];
        ChromeExtensionsAccessPartialDenyUrlList = strArr[203];
        ChromeExtensionsWhiteList = strArr[243];
        ChromeExtensionsBlackList = strArr[242];
        ChromeExtensionsEnabled = strArr[27];
        CrxAddDefaultViewportOnPopupPage = strArr[26];
        ChromeExtensionsMV2AutoReload = strArr[29];
        IgnoreViewportMetaList = strArr[256];
        ChromeExtensionInstallMapping = strArr[204];
        CrxStatsEnabled = strArr[39];
        CrxForceMediaResourceSniffing = strArr[28];
        EnableBindPerformanceCore = strArr[36];
        CommonLibDir = strArr[171];
    }
}
