package com.alipay.mobile.verifyidentity.module;

import com.alipay.mobile.verifyidentity.common.ModuleConstants;
import com.android.alibaba.ip.runtime.IpChange;
import java.util.ArrayList;
import java.util.List;

/* compiled from: Taobao */
/* loaded from: /Users/corson/Downloads/taobao_decompiled/build/apk/classes3.dex */
public class ModuleMetaInfo {
    public static volatile transient /* synthetic */ IpChange $ipChange;

    /* renamed from: a  reason: collision with root package name */
    public final List<ModuleDescription> f4308a;

    public ModuleMetaInfo() {
        ArrayList arrayList = new ArrayList();
        this.f4308a = arrayList;
        ModuleDescription moduleDescription = new ModuleDescription();
        moduleDescription.setModuleName(ModuleConstants.VI_MODULE_MENU);
        moduleDescription.setClassName("com.alipay.mobile.verifyidentity.module.menu.MenuModule");
        arrayList.add(moduleDescription);
        ModuleDescription moduleDescription2 = new ModuleDescription();
        moduleDescription2.setModuleName(ModuleConstants.VI_MODULE_INTERNAL_MENU);
        moduleDescription2.setClassName("com.alipay.mobile.verifyidentity.module.menu.MenuModule");
        arrayList.add(moduleDescription2);
        ModuleDescription moduleDescription3 = new ModuleDescription();
        moduleDescription3.setModuleName(ModuleConstants.VI_MODULE_NAME_PRIVACY_QUESTION);
        moduleDescription3.setClassName("com.alipay.mobile.verifyidentity.module.shield.ShieldModule");
        arrayList.add(moduleDescription3);
        ModuleDescription moduleDescription4 = new ModuleDescription();
        moduleDescription4.setModuleName(ModuleConstants.VI_MODULE_NAME_SAFE_AREA);
        moduleDescription4.setClassName("com.alipay.mobile.verifyidentity.module.safezone.SafeZoneModule");
        arrayList.add(moduleDescription4);
        ModuleDescription moduleDescription5 = new ModuleDescription();
        moduleDescription5.setModuleName(ModuleConstants.VI_MODULE_SIGN_LOGIN_FACE);
        moduleDescription5.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription5);
        ModuleDescription moduleDescription6 = new ModuleDescription();
        moduleDescription6.setModuleName(ModuleConstants.VI_MODULE_LOGIN_FACE);
        moduleDescription6.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription6);
        ModuleDescription moduleDescription7 = new ModuleDescription();
        moduleDescription7.setModuleName(ModuleConstants.VI_MODULE_NAME_BANKCARD_BINDING);
        moduleDescription7.setClassName("com.alipay.mobile.verifyidentity.module.bankcard.BankCardModule");
        arrayList.add(moduleDescription7);
        ModuleDescription moduleDescription8 = new ModuleDescription();
        moduleDescription8.setModuleName(ModuleConstants.VI_MODULE_NAME_BANK_RISK_BINGING);
        moduleDescription8.setClassName("com.alipay.mobile.verifyidentity.module.bankcard.MspBankCardModule");
        arrayList.add(moduleDescription8);
        ModuleDescription moduleDescription9 = new ModuleDescription();
        moduleDescription9.setModuleName(ModuleConstants.VI_MODULE_NAME_NO_CAPTCHA);
        moduleDescription9.setClassName("com.alipay.mobile.verifyidentity.module.nocaptcha.NoCaptchaModule");
        arrayList.add(moduleDescription9);
        ModuleDescription moduleDescription10 = new ModuleDescription();
        moduleDescription10.setModuleName(ModuleConstants.VI_MODULE_NAME_ACCOUNT_CERT_FACE);
        moduleDescription10.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription10);
        ModuleDescription moduleDescription11 = new ModuleDescription();
        moduleDescription11.setModuleName(ModuleConstants.VI_MODULE_NAME_SYS_INPUT_CERT_FACE);
        moduleDescription11.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription11);
        ModuleDescription moduleDescription12 = new ModuleDescription();
        moduleDescription12.setModuleName(ModuleConstants.VI_MODULE_NAME_X_ACCOUNT_CERT_FACE);
        moduleDescription12.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription12);
        ModuleDescription moduleDescription13 = new ModuleDescription();
        moduleDescription13.setModuleName(ModuleConstants.VI_MODULE_NAME_FACEVERIFY);
        moduleDescription13.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription13);
        ModuleDescription moduleDescription14 = new ModuleDescription();
        moduleDescription14.setModuleName(ModuleConstants.VI_MODULE_INTERNAL_FACE);
        moduleDescription14.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription14);
        ModuleDescription moduleDescription15 = new ModuleDescription();
        moduleDescription15.setModuleName(ModuleConstants.VI_MODULE_NAME_IDFACE);
        moduleDescription15.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription15);
        ModuleDescription moduleDescription16 = new ModuleDescription();
        moduleDescription16.setModuleName(ModuleConstants.VI_MODULE_NAME_IDPAPERS);
        moduleDescription16.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription16);
        ModuleDescription moduleDescription17 = new ModuleDescription();
        moduleDescription17.setModuleName(ModuleConstants.VI_MODULE_NAME_PAY_PWD);
        moduleDescription17.setClassName("com.alipay.mobile.verifyidentity.module.password.pay.PayPwdModule");
        arrayList.add(moduleDescription17);
        ModuleDescription moduleDescription18 = new ModuleDescription();
        moduleDescription18.setModuleName(ModuleConstants.VI_MODULE_INTERNAL_NAME_PPW);
        moduleDescription18.setClassName("com.alipay.mobile.verifyidentity.module.internal.password.pay.PayPwdModule");
        arrayList.add(moduleDescription18);
        ModuleDescription moduleDescription19 = new ModuleDescription();
        moduleDescription19.setModuleName(ModuleConstants.VI_MODULE_NAME_PAYMENT_PASSWORD_PLUS);
        moduleDescription19.setClassName("com.alipay.mobile.verifyidentity.module.fingerprint.FingerprintModule");
        arrayList.add(moduleDescription19);
        ModuleDescription moduleDescription20 = new ModuleDescription();
        moduleDescription20.setModuleName(ModuleConstants.VI_MODULE_INTERNAL_NAME_PAYMENT_PASSWORD_PLUS);
        moduleDescription20.setClassName("com.alipay.mobile.verifyidentity.module.fingerprint.FingerprintModule");
        arrayList.add(moduleDescription20);
        ModuleDescription moduleDescription21 = new ModuleDescription();
        moduleDescription21.setModuleName(ModuleConstants.VI_MODULE_NAME_SMS);
        moduleDescription21.setClassName("com.alipay.mobile.verifyidentity.module.sms.SmsModule");
        arrayList.add(moduleDescription21);
        ModuleDescription moduleDescription22 = new ModuleDescription();
        moduleDescription22.setModuleName(ModuleConstants.VI_MODULE_NAME_ACCOUNT_SMS);
        moduleDescription22.setClassName("com.alipay.mobile.verifyidentity.module.sms.SmsModule");
        arrayList.add(moduleDescription22);
        ModuleDescription moduleDescription23 = new ModuleDescription();
        moduleDescription23.setModuleName(ModuleConstants.VI_MODULE_NAME_CUSTOMIZED_SMS);
        moduleDescription23.setClassName("com.alipay.mobile.verifyidentity.module.sms.SmsModule");
        arrayList.add(moduleDescription23);
        ModuleDescription moduleDescription24 = new ModuleDescription();
        moduleDescription24.setModuleName(ModuleConstants.VI_MODULE_NAME_NAME_BIRTHDAY);
        moduleDescription24.setClassName("com.alipay.mobile.verifyidentity.module.namebirthday.NameBirthdayModule");
        arrayList.add(moduleDescription24);
        ModuleDescription moduleDescription25 = new ModuleDescription();
        moduleDescription25.setModuleName(ModuleConstants.VI_MODULE_NAME_ALILANG_FACE);
        moduleDescription25.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription25);
        ModuleDescription moduleDescription26 = new ModuleDescription();
        moduleDescription26.setModuleName(ModuleConstants.VI_MODULE_NAME_ALIFACE);
        moduleDescription26.setClassName("com.alipay.module.face.AliFaceCertModule");
        arrayList.add(moduleDescription26);
        ModuleDescription moduleDescription27 = new ModuleDescription();
        moduleDescription27.setModuleName(ModuleConstants.VI_MODULE_NAME_MOBILE_CERT);
        moduleDescription27.setClassName("com.alipay.mobile.verifyidentity.module.cert.CertModule");
        arrayList.add(moduleDescription27);
        ModuleDescription moduleDescription28 = new ModuleDescription();
        moduleDescription28.setModuleName(ModuleConstants.VI_MODULE_NAME_HAND_WRITING);
        moduleDescription28.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription28);
        ModuleDescription moduleDescription29 = new ModuleDescription();
        moduleDescription29.setModuleName(ModuleConstants.VI_MODULE_NAME_PAPERS);
        moduleDescription29.setClassName("com.alipay.module.face.BaseFaceCertModule");
        arrayList.add(moduleDescription29);
        ModuleDescription moduleDescription30 = new ModuleDescription();
        moduleDescription30.setModuleName(ModuleConstants.VI_MODULE_NAME_DYNAMIC_CENTER);
        moduleDescription30.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription30);
        ModuleDescription moduleDescription31 = new ModuleDescription();
        moduleDescription31.setModuleName(ModuleConstants.VI_MODULE_NAME_SECRET_QUESTION);
        moduleDescription31.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription31);
        ModuleDescription moduleDescription32 = new ModuleDescription();
        moduleDescription32.setModuleName(ModuleConstants.VI_MODULE_NAME_SMS);
        moduleDescription32.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription32);
        ModuleDescription moduleDescription33 = new ModuleDescription();
        moduleDescription33.setModuleName(ModuleConstants.VI_MODULE_NAME_ACCOUNT_SMS);
        moduleDescription33.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription33);
        ModuleDescription moduleDescription34 = new ModuleDescription();
        moduleDescription34.setModuleName(ModuleConstants.VI_MODULE_NAME_CUSTOMIZED_SMS);
        moduleDescription34.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription34);
        ModuleDescription moduleDescription35 = new ModuleDescription();
        moduleDescription35.setModuleName(ModuleConstants.VI_MODULE_NAME_PRIVACY_QUESTION);
        moduleDescription35.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription35);
        ModuleDescription moduleDescription36 = new ModuleDescription();
        moduleDescription36.setModuleName(ModuleConstants.VI_MODULE_NAME_REGISTER_CERTIFICATE);
        moduleDescription36.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription36);
        ModuleDescription moduleDescription37 = new ModuleDescription();
        moduleDescription37.setModuleName(ModuleConstants.VI_MODULE_NAME_FAST_PAY_PRIVACY);
        moduleDescription37.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription37);
        ModuleDescription moduleDescription38 = new ModuleDescription();
        moduleDescription38.setModuleName(ModuleConstants.VI_MODULE_NAME_FAST_PAY_PRIVACY_7DAY);
        moduleDescription38.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription38);
        ModuleDescription moduleDescription39 = new ModuleDescription();
        moduleDescription39.setModuleName(ModuleConstants.VI_MODULE_AUTH_CODE);
        moduleDescription39.setClassName("com.alipay.mobile.verifyidentity.module.qrcode.QrCodeModule");
        arrayList.add(moduleDescription39);
        ModuleDescription moduleDescription40 = new ModuleDescription();
        moduleDescription40.setModuleName(ModuleConstants.VI_MODULE_NAME_REMIND);
        moduleDescription40.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription40);
        ModuleDescription moduleDescription41 = new ModuleDescription();
        moduleDescription41.setModuleName(ModuleConstants.VI_MODULE_NAME_REMIND_QUIZZES);
        moduleDescription41.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription41);
        ModuleDescription moduleDescription42 = new ModuleDescription();
        moduleDescription42.setModuleName(ModuleConstants.VI_MODULE_NAME_REMIND_GRAPHIC);
        moduleDescription42.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription42);
        ModuleDescription moduleDescription43 = new ModuleDescription();
        moduleDescription43.setModuleName(ModuleConstants.VI_MODULE_IDNO_INTERNAL);
        moduleDescription43.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription43);
        ModuleDescription moduleDescription44 = new ModuleDescription();
        moduleDescription44.setModuleName(ModuleConstants.VI_MODULE_CC_PAINTEXT_HK_INTERNAL);
        moduleDescription44.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription44);
        ModuleDescription moduleDescription45 = new ModuleDescription();
        moduleDescription45.setModuleName(ModuleConstants.VI_MODULE_BANK_CARD_RISK);
        moduleDescription45.setClassName("com.alipay.mobile.verifyidentity.module.dynamic.DynamicModule");
        arrayList.add(moduleDescription45);
        ModuleDescription moduleDescription46 = new ModuleDescription();
        moduleDescription46.setModuleName(ModuleConstants.VI_MODULE_NAME_REMIND_IMMUNE);
        moduleDescription46.setClassName("com.alipay.mobile.verifyidentity.module.immune.ImmuneModule");
        arrayList.add(moduleDescription46);
        ModuleDescription moduleDescription47 = new ModuleDescription();
        moduleDescription47.setModuleName(ModuleConstants.VI_MODULE_NAME_PHONE_SIM);
        moduleDescription47.setClassName("com.alipay.mobile.verifyidentity.module.phone_sim.PhoneSIMModule");
        arrayList.add(moduleDescription47);
        ModuleDescription moduleDescription48 = new ModuleDescription();
        moduleDescription48.setModuleName(ModuleConstants.VI_MODULE_SE_CERT);
        moduleDescription48.setClassName("com.alipay.mobile.verifyidentity.module.visecert.VISECertModule");
        arrayList.add(moduleDescription48);
        ModuleDescription moduleDescription49 = new ModuleDescription();
        moduleDescription49.setModuleName(ModuleConstants.VI_MODULE_NAME_SECCAM_FACEVERIFY);
        moduleDescription49.setClassName("com.alipay.mobile.verifyidentity.module.seccam.SecCamModule");
        arrayList.add(moduleDescription49);
    }

    public List<ModuleDescription> getModules() {
        IpChange ipChange = $ipChange;
        if (ipChange instanceof IpChange) {
            return (List) ipChange.ipc$dispatch("37895fef", new Object[]{this});
        }
        return this.f4308a;
    }
}
