package com.uc.webview.base;

import com.ali.user.mobile.ui.WebConstant;
import com.alibaba.triver.triver_shop.shop2023.nativeview.Shop2023BottomBarNativeComponent;
import com.alibaba.wireless.security.SecExceptionCode;
import com.alipay.android.phone.mobilesdk.socketcraft.api.WSContextConstant;
import com.alipay.security.mobile.alipayauthenticatorservice.message.Result;
import com.taobao.android.alinnkit.entity.FaceDetectionReport;
import com.taobao.artc.api.AConstants;
import com.taobao.artc.internal.ArtcParams;
import com.taobao.metrickit.event.lifecycle.LifecycleEventSource;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import tb.gyb;
import tb.mct;
import tb.ra;
import tb.tck;

/* compiled from: Taobao */
/* loaded from: /Users/corson/Downloads/taobao_decompiled/build/apk/classes9.dex */
public class KeyIdMap {

    /* renamed from: a  reason: collision with root package name */
    public static final String[] f14251a;
    public static final String[] b;
    static final Map<Integer, int[]> e = new HashMap<Integer, int[]>() { // from class: com.uc.webview.base.KeyIdMap.1
        {
            put(111, new int[]{0, 1});
            put(112, new int[]{-1, 0, 1, 2});
            put(121, new int[]{-1, 0, 1, 2});
            put(126, new int[]{-1, 0, 1, 3, 4});
            put(130, new int[]{0, 1, 2});
            put(131, new int[]{-1, 0, 1, 2, 11, 12, -1, 0, 1, 2});
            put(132, new int[]{1, 2, 3, 4});
            put(133, new int[]{0, 1, 2, 3, 4, 5});
            put(161, new int[]{2, 3, 4});
            put(Integer.valueOf((int) Shop2023BottomBarNativeComponent.bottomBarHeightWithBottomMarginRpxValue), new int[]{0, 1, 2, 3});
            put(166, new int[]{0, 1, 2});
        }
    };
    public static final int[][] c = {new int[]{0, 111}, new int[]{111, 171}, new int[]{171, 171}, new int[]{171, 227}, new int[]{227, 280}};
    static final int[] d = {7, 22, 24, 26, 27, 28, 29, 31, 36, 46, 78, 90, 99, 112, 126, 134, 135, 152, Shop2023BottomBarNativeComponent.bottomBarHeightWithBottomMarginRpxValue, 164, 166, 168, 187, 188, WSContextConstant.HANDSHAKE_SEND_SIZE, 190, 191, 202, 203, 204, 205, 212, LifecycleEventSource.ON_FRAGMENT_DESTROYED, 214, 231, 242, 243, 256, 264};

    /* compiled from: Taobao */
    /* loaded from: /Users/corson/Downloads/taobao_decompiled/build/apk/classes9.dex */
    public static class a {

        /* renamed from: a  reason: collision with root package name */
        private static final Map<String, Integer> f14252a = new HashMap<String, Integer>() { // from class: com.uc.webview.base.KeyIdMap.a.1
            {
                String[] strArr = KeyIdMap.f14251a;
                put(strArr[0], 0);
                put(strArr[1], 1);
                put(strArr[2], 2);
                put(strArr[3], 3);
                put(strArr[4], 4);
                put(strArr[5], 5);
                put(strArr[6], 6);
                put(strArr[7], 7);
                put(strArr[8], 8);
                put(strArr[9], 9);
                put(strArr[10], 10);
                put(strArr[11], 11);
                put(strArr[12], 12);
                put(strArr[13], 13);
                put(strArr[14], 14);
                put(strArr[15], 15);
                put(strArr[16], 16);
                put(strArr[17], 17);
                put(strArr[18], 18);
                put(strArr[19], 19);
                put(strArr[20], 20);
                put(strArr[21], 21);
                put(strArr[22], 22);
                put(strArr[23], 23);
                put(strArr[24], 24);
                put(strArr[25], 25);
                put(strArr[26], 26);
                put(strArr[27], 27);
                put(strArr[28], 28);
                put(strArr[29], 29);
                put(strArr[30], 30);
                put(strArr[31], 31);
                put(strArr[32], 32);
                put(strArr[33], 33);
                put(strArr[34], 34);
                put(strArr[35], 35);
                put(strArr[36], 36);
                put(strArr[37], 37);
                put(strArr[38], 38);
                put(strArr[39], 39);
                put(strArr[40], 40);
                put(strArr[41], 41);
                put(strArr[42], 42);
                put(strArr[43], 43);
                put(strArr[44], 44);
                put(strArr[45], 45);
                put(strArr[46], 46);
                put(strArr[47], 47);
                put(strArr[48], 48);
                put(strArr[49], 49);
                put(strArr[50], 50);
                put(strArr[51], 51);
                put(strArr[52], 52);
                put(strArr[53], 53);
                put(strArr[54], 54);
                put(strArr[55], 55);
                put(strArr[56], 56);
                put(strArr[57], 57);
                put(strArr[58], 58);
                put(strArr[59], 59);
                put(strArr[60], 60);
                put(strArr[61], 61);
                put(strArr[62], 62);
                put(strArr[63], 63);
                put(strArr[64], 64);
                put(strArr[65], 65);
                put(strArr[66], 66);
                put(strArr[67], 67);
                put(strArr[68], 68);
                put(strArr[69], 69);
                put(strArr[70], 70);
                put(strArr[71], 71);
                put(strArr[72], 72);
                put(strArr[73], 73);
                put(strArr[74], 74);
                put(strArr[75], 75);
                put(strArr[76], 76);
                put(strArr[77], 77);
                put(strArr[78], 78);
                put(strArr[79], 79);
                put(strArr[80], 80);
                put(strArr[81], 81);
                put(strArr[82], 82);
                put(strArr[83], 83);
                put(strArr[84], 84);
                put(strArr[85], 85);
                put(strArr[86], 86);
                put(strArr[87], 87);
                put(strArr[88], 88);
                put(strArr[89], 89);
                put(strArr[90], 90);
                put(strArr[91], 91);
                put(strArr[92], 92);
                put(strArr[93], 93);
                put(strArr[94], 94);
                put(strArr[95], 95);
                put(strArr[96], 96);
                put(strArr[97], 97);
                put(strArr[98], 98);
                put(strArr[99], 99);
                put(strArr[100], 100);
                put(strArr[101], 101);
                put(strArr[102], 102);
                put(strArr[103], 103);
                put(strArr[104], 104);
                put(strArr[105], 105);
                put(strArr[106], 106);
                put(strArr[107], 107);
                put(strArr[108], 108);
                put(strArr[109], 109);
                put(strArr[110], 110);
                put(strArr[111], 111);
                put(strArr[112], 112);
                put(strArr[113], 113);
                put(strArr[114], 114);
                put(strArr[115], 115);
                put(strArr[116], 116);
                put(strArr[117], 117);
                put(strArr[118], 118);
                put(strArr[119], 119);
                put(strArr[120], 120);
                put(strArr[121], 121);
                put(strArr[122], 122);
                put(strArr[123], 123);
                put(strArr[124], 124);
                put(strArr[125], 125);
                put(strArr[126], 126);
                put(strArr[127], 127);
                put(strArr[128], 128);
                put(strArr[129], 129);
                put(strArr[130], 130);
                put(strArr[131], 131);
                put(strArr[132], 132);
                put(strArr[133], 133);
                put(strArr[134], 134);
                put(strArr[135], 135);
                put(strArr[136], 136);
                put(strArr[137], 137);
                put(strArr[138], Integer.valueOf((int) SecExceptionCode.SEC_ERROR_INIT_PLUGIN_CLASS_ERROR));
                put(strArr[139], Integer.valueOf((int) SecExceptionCode.SEC_ERROR_INIT_CLAZZ_NULL_ERROR));
                put(strArr[140], Integer.valueOf((int) SecExceptionCode.SEC_ERROR_INIT_DELAY_REPORT_ERROR));
                put(strArr[141], 141);
                put(strArr[142], Integer.valueOf((int) SecExceptionCode.SEC_ERROR_INIT_PLUGIN_MERGED_MIDDLE_TIER_ERROR));
                put(strArr[143], Integer.valueOf((int) SecExceptionCode.SEC_ERROR_INIT_PLUGIN_MERGED_INIT_CONFIG_MODIFY_ERROR));
                put(strArr[144], 144);
                put(strArr[145], Integer.valueOf((int) ra.INSTALL_PROVIDER));
                put(strArr[146], 146);
                put(strArr[147], 147);
                put(strArr[148], 148);
                put(strArr[149], 149);
                put(strArr[150], 150);
                put(strArr[151], 151);
                put(strArr[152], 152);
                put(strArr[153], 153);
                put(strArr[154], 154);
                put(strArr[155], Integer.valueOf((int) mct.USTAR_FILENAME_PREFIX));
                put(strArr[156], 156);
                put(strArr[157], 157);
                put(strArr[158], 158);
                put(strArr[159], 159);
                put(strArr[160], 160);
                put(strArr[161], 161);
                put(strArr[162], Integer.valueOf((int) Shop2023BottomBarNativeComponent.bottomBarHeightWithBottomMarginRpxValue));
                put(strArr[163], 163);
                put(strArr[164], 164);
                put(strArr[165], 165);
                put(strArr[166], 166);
                put(strArr[167], 167);
                put(strArr[168], 168);
                put(strArr[169], 169);
                put(strArr[170], 170);
                put(strArr[171], 171);
                put(strArr[172], 172);
                put(strArr[173], Integer.valueOf((int) com.taobao.trtc.rtcroom.a.DEFAULT_FLOATING_WINDOW_HEIGHT));
                put(strArr[174], 174);
                put(strArr[175], 175);
                put(strArr[176], Integer.valueOf((int) ArtcParams.SD180pVideoParams.HEIGHT));
                put(strArr[177], 177);
                put(strArr[178], 178);
                put(strArr[179], 179);
                put(strArr[180], 180);
                put(strArr[181], 181);
                put(strArr[182], 182);
                put(strArr[183], 183);
                put(strArr[184], 184);
                put(strArr[185], Integer.valueOf((int) WSContextConstant.HANDSHAKE_RECEIVE_SIZE));
                put(strArr[186], 186);
                put(strArr[187], 187);
                put(strArr[188], 188);
                put(strArr[189], Integer.valueOf((int) WSContextConstant.HANDSHAKE_SEND_SIZE));
                put(strArr[190], 190);
                put(strArr[191], 191);
                put(strArr[192], Integer.valueOf((int) tck.DETECT_WIDTH));
                put(strArr[193], 193);
                put(strArr[194], 194);
                put(strArr[195], 195);
                put(strArr[196], 196);
                put(strArr[197], 197);
                put(strArr[198], 198);
                put(strArr[199], 199);
                put(strArr[200], 200);
                put(strArr[201], 201);
                put(strArr[202], 202);
                put(strArr[203], 203);
                put(strArr[204], 204);
                put(strArr[205], 205);
                put(strArr[206], 206);
                put(strArr[207], Integer.valueOf((int) SecExceptionCode.SEC_ERROR_STA_STORE_ILLEGEL_KEY));
                put(strArr[208], 208);
                put(strArr[209], 209);
                put(strArr[210], 210);
                put(strArr[211], 211);
                put(strArr[212], 212);
                put(strArr[213], Integer.valueOf((int) LifecycleEventSource.ON_FRAGMENT_DESTROYED));
                put(strArr[214], 214);
                put(strArr[215], 215);
                put(strArr[216], 216);
                put(strArr[217], 217);
                put(strArr[218], 218);
                put(strArr[219], 219);
                put(strArr[220], 220);
                put(strArr[221], Integer.valueOf((int) AConstants.ArtcErrorServerErrorDropByMobility));
                put(strArr[222], 222);
                put(strArr[223], 223);
                put(strArr[224], 224);
                put(strArr[225], 225);
                put(strArr[226], 226);
                put(strArr[227], 227);
                put(strArr[228], 228);
                put(strArr[229], 229);
                put(strArr[230], 230);
                put(strArr[231], 231);
                put(strArr[232], 232);
                put(strArr[233], 233);
                put(strArr[234], 234);
                put(strArr[235], 235);
                put(strArr[236], 236);
                put(strArr[237], 237);
                put(strArr[238], 238);
                put(strArr[239], 239);
                put(strArr[240], 240);
                put(strArr[241], 241);
                put(strArr[242], 242);
                put(strArr[243], 243);
                put(strArr[244], Integer.valueOf((int) ArtcParams.SD244pVideoParams.WIDTH));
                put(strArr[245], 245);
                put(strArr[246], 246);
                put(strArr[247], 247);
                put(strArr[248], 248);
                put(strArr[249], 249);
                put(strArr[250], 250);
                put(strArr[251], 251);
                put(strArr[252], 252);
                put(strArr[253], 253);
                put(strArr[254], 254);
                put(strArr[255], 255);
                put(strArr[256], 256);
                put(strArr[257], 257);
                put(strArr[258], Integer.valueOf((int) WebConstant.OPEN_WEB_RESCODE));
                put(strArr[259], Integer.valueOf((int) gyb.ERROR_MTOP_SERVICE_EXCEPTION));
                put(strArr[260], 260);
                put(strArr[261], 261);
                put(strArr[262], 262);
                put(strArr[263], 263);
                put(strArr[264], 264);
                put(strArr[265], 265);
                put(strArr[266], 266);
                put(strArr[267], 267);
                put(strArr[268], Integer.valueOf((int) FaceDetectionReport.NATIVE_EXTRA_FLOAT_OUT_LENGTH));
                put(strArr[269], 269);
                put(strArr[270], 270);
                put(strArr[271], 271);
                put(strArr[272], 272);
                put(strArr[273], Integer.valueOf((int) Result.ALIPAY_GET_HARD_DEVICE_ID_ERROR));
                put(strArr[274], Integer.valueOf((int) Result.ALIPAY_PARAM_INVALID));
                put(strArr[275], Integer.valueOf((int) Result.ALIPAY_RSAKEY_MALLOC_FAILED));
                put(strArr[276], 276);
                put(strArr[277], Integer.valueOf((int) Result.ALIPAY_GET_FP_INDEX_FAILED));
                put(strArr[278], Integer.valueOf((int) Result.ALIPAY_GENERATE_REG_NODE_FAILED));
                put(strArr[279], Integer.valueOf((int) Result.ALIPAY_VERIFY_REG_NODE_FAILED));
            }
        };
    }

    static {
        String[] strArr = {"CachePageFreeFirstThanKeep", "CustomFont", "DisableBFCache", "DiscardableReleaseFreeAfterTimeSwitch", "DistinguishJSError", "EnableAdBlock", "EnableForceDefaultVLinkColor", "EnableInRendererGpu", "EnableSameSiteCookieDegradation", "ForceEnableUserSelect", "IsHardwareAC", "IsNightMode", "IsNoFootmark", "IsRunningInWebViewSdk", "OpenCacheLog", "ReloadIfUAChanged", "adaptive_layout_enable", "allow_commit_all_perf_data", "audio_output_use_aaudio", "auth_media_js_api", "block_background_media_play", "capture_enable_wait_load", "crjz_enbr", "crjz_nh", "crjz_nhddi", "crwp_embed_view_stats_enable", "crx_add_vp_on_popup_page", "crx_enable", "crx_force_media_res_sniff", "crx_mv2_auto_reload", "crxr_disable_image_view", "custom_font", "decode_fail_is_on", "disable_aaudio", "disable_exit_fullscreen_when_js_prompt", "disable_js_fullscreen_when_hybrid", "enable_bind_performace_core", "enable_block_navigation", "enable_con_undef_stats", "enable_crx_stats", "enable_debugging", "enable_fd_sanitizer", "enable_feature_stats", "enable_file_empty_screen_check", "enable_fit_screen_text_wrap", "enable_gpu_process_on_low_end_device", "enable_hittest_prefetch", "enable_hosting_http_cache", "enable_keyword_hyperlink", "enable_keyword_hyperlink_stat", "enable_klog", "enable_lottie", "enable_lottie_stats_url", "enable_low_latency_compat", "enable_mse_use_hybrid", "enable_performance_mark_timimg", "enable_run_in_seperate_thread", "enable_should_intercept_request", "enable_snapshot_background_deserialize", "enable_snapshot_by_url", "enable_snapshot_script_resource_cache", "enable_timing_tti", "enable_undefine_stats", "enable_v8_context_snapshot", "enable_webrtc_h265", "enable_webview_event_empty_screen", "enalbe_mse_adaptive", "ext_img_decoder_on", "ignore_touch_on_floating_win", "non_hybrid_for_muted_and_no_controls", "password_fill_prompt_on_load", "pin_zoom_stats_enable", "prerender_pending_load_event", "remove_image_from_cache", "send_decode_fail_webview_event", "temp_kuying_check_with_port", "u4sdk_dsal", "u4sdk_ena_sts", "u4sdk_enable_cdve", "u4sdk_enable_dlcl", "u4sdk_enable_ifcl", "u4sdk_enable_lcrd", "u4sdk_enable_wvcit", "u4sdk_enltcc", "u4sdk_enltl", "u4sdk_enncd", "u4sdk_enpsce", "u4sdk_enpscea", "u4sdk_enrlc", "u4sdk_enrne", "u4sdk_enspc", "u4sdk_enwvwu", "u4sdk_enx86d", "u4sdk_eute", "u4sdk_ics", "u4sdk_iffs", "u4sdk_is_interver", "u4sdk_pldckmgr", "u4sdk_sts_spl", "u4sdk_udc", "u4sdk_use_ucp", "u4sdk_wvls", "verbose_backtrace", "video_disable_meta_autoplay", "video_enable_auto_landscape", "video_enable_below_fixed", "video_enable_mse", "video_hardward_accelerate", "video_ignore_play_when_visible", "webaudio_user_gesture_required", "wpk_stat_pv", "AppMode", "BackupRenderWarmupStrategy", "CachePageNumber", "CachePageNumberOnCritical", "CachePageNumberOnModerate", "DiscardableDataKeepSecond", "DiscardableLimitBytes", "DiscardableReleaseFreeAfterSecond", "DiscardableReleaseFreeUntilByte", "FormSave", "GpuProcMode", "GrDiscardableLimitByte", "GrDiscardableLowEndLimitByte", "GrResourceCacheLimitByte", "GrResourceCacheLowEndLimitByte", "IsolateRenderWarmupStrategy", "LayoutStyle", "LinkUnderline", "MediaCodecType", "RenderPipelineType", "RenderProcMode", "UCCookieType", "activity_status", "cpn_dlt", "cpn_nu_ctrl", "custom_attributes_control_type", "extend_view_auto_float_min_duration", "h264_encoder_type", "hybrid_covered_check_type", "keyword_hyperlink_count", "keyword_hyperlink_interval", "keyword_hyperlink_length", "longpress_timeout_ms", "max_dom_tree_depth", "max_web_worker_count_for_bfcache", "mse_list_type", "select_popup_top_margin", "should_intercept_request_timeout_limit", "show_media_extend_view_type", "show_native_ctrl_when_loading_type", "t1t3detail_sample_rate", "t2_finish_timeout", "u4sdk_adrc", "u4sdk_apd", "u4sdk_asrc", "u4sdk_atrc", "u4sdk_ecif", "u4sdk_hcrto", "u4sdk_hcto", "u4sdk_iwvwm", "u4sdk_nldt", "u4sdk_patch_mode", "u4sdk_pincdm", "u4sdk_rlcvs", "u4sdk_sts_uli", "u4sdk_vfp", "v8_code_cache_threshold_mb", "v8_snapshot_header_version", "wpk_stat_sample_rate", "xhr_sync_timeout_limit", "CommonLibDir", "CommonLibParsName", "CookiesBlacklistForJs", "CoreDexPath", "CoreLibPath", "CoreOdexPath", "GlobalDefaultUserAgent", "GlobalWebviewUA", "GwpAsanConfig", "UBISiLang", "UBISiVersion", "UBISn", "UBIUtdId", "apollo_settings", "ax_support_service_list", "bpg_lib_path", "core_thread_watchdog_alarm_duration", "core_thread_watchdog_dump_js_rate", "core_thread_watchdog_dump_native_rate", "core_thread_watchdog_watch_list", "cpn_dl_crest", "crjz_block_request_rule", "crjz_nh_crret", "crjz_nh_ret", "crjz_nh_usm", "crpb_ihjs", "crpb_ihjs_url", "crsp_adffso", "crsp_mpplgs", "crwp_embed_view_surface_detect_config", "crwp_embed_view_transparent_type_list", "crx_access_deny_url_list", "crx_access_partial_deny_url_list", "crx_install_mapping", "crx_self_biz_url_list", "keyword_hyperlink_channel_distribution", "keyword_hyperlink_sensitive_words", "last_user_input_time", "media_player_limits", "network_hosting_instance_v1", "private_data_dir_suffix", "snapshot_react16_urls", "snapshot_react17_urls", "snapshot_react18_urls", "t2_stat_render_process_bound", "t2_stat_render_process_connected", "u4sdk_aet", "u4sdk_apd", "u4sdk_ebts", "u4sdk_ests", "u4sdk_sall", "u4sdk_sts_ils", "u4sdk_sts_its", "u4sdk_sts_uct", "video_disable_extend_view_titles", "wpk_u4statline", "adaptive_layout_blacklist", "allow_js_set_info_list", "allow_popup_list", "bwlist_ewu_urls", "bwlist_upld_statkeys", "crjs_hide_ucweb_black_list", "crjz_cors_v8wh", "crjz_cors_whitelist", "crjz_cors_whitelist_core", "crjz_nh_ush_list", "crpb_ihhl", "crsp_dcj_wl", "crwp_embed_view_embed_surface_enable_list", "crwp_embed_view_hybrid_render_enable_list", "crwp_embed_view_reattach_list", "crx_black_list", "crx_white_list", "disable_alive_player_limit", "disable_autoplay_mac", "disable_autoplay_man", "disable_mse_adaptive_list", "disable_show_native_ctrl_when_loading", "enable_before_play_callback_list", "enable_get_cache_file_list", "enable_preload_video_based_rh", "enable_preload_video_source_list", "enable_video_super_toolbar", "fit_screen_text_wrap_blacklist", "hybrid_covered_check_block_list", "ignore_viewport_meta_list", "jsapi_async_function_list", "keyword_hyperlink_blacklist", "local_enable_mse", "local_video_disable_extend_view_float", "mse_hybrid_white_list", "non_internal_bussiness_bids", "u4_focus_auto_popup_input_list", "u4sdk_fccbl", "u4xr_mse_list", "u4xr_video_st_list", "u4xr_video_stats_list", "u4xr_video_view_under_webview", "video_custom_attributes_white_list", "video_disable_embedded_floating", "video_disable_extend_view_float", "video_disable_mse", "video_enable_precise_seek", "video_ignore_first_pos", "video_ignore_seek_to_end", "video_play_gesture_whitelist", "video_popstate_disable", "video_use_surface_view", "webkitvisibilitychange_disable_whitelist"};
        f14251a = strArr;
        b = new String[]{strArr[22], strArr[27], strArr[76], strArr[77], strArr[78], strArr[79], strArr[80], strArr[81], strArr[83], strArr[84], strArr[85], strArr[86], strArr[87], strArr[88], strArr[89], strArr[90], strArr[91], strArr[92], strArr[93], strArr[94], strArr[95], strArr[97], strArr[98], strArr[100], strArr[130], strArr[134], strArr[135], strArr[157], strArr[158], strArr[159], strArr[160], strArr[161], strArr[162], strArr[163], strArr[164], strArr[166], strArr[187], strArr[188], strArr[189], strArr[190], strArr[191], strArr[202], strArr[203], strArr[205], strArr[220], strArr[221], strArr[222], strArr[223], strArr[242], strArr[243], strArr[264]};
    }

    public static Set<String> a() {
        return a.f14252a.keySet();
    }

    public static int getId(String str) {
        if (a.f14252a.containsKey(str)) {
            return ((Integer) a.f14252a.get(str)).intValue();
        }
        return -1;
    }
}
