package com.alibaba.android.split.scene;

import com.taobao.android.live.plugin.proxy.FlexaLiveX;
import com.taobao.appbundle.a;
import java.util.ArrayList;
import java.util.HashMap;
import tb.obq;
import tb.tbt;
import tb.u58;
import tb.x8c;

/* compiled from: Taobao */
/* loaded from: /Users/corson/Downloads/taobao_decompiled/build/apk/classes2.dex */
public class FeatureSceneInfoGenerator implements x8c {
    @Override // tb.x8c
    public HashMap<String, HashMap<String, ArrayList<String>>> generate() {
        HashMap<String, HashMap<String, ArrayList<String>>> hashMap = new HashMap<>();
        HashMap<String, ArrayList<String>> hashMap2 = new HashMap<>();
        hashMap.put("com.taobao.search.searchdoor.SearchDoorActivity", hashMap2);
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("tbsearch_remote");
        arrayList.add("taowise_android_aar");
        arrayList.add("voice_assistant");
        hashMap2.put("default", arrayList);
        HashMap<String, ArrayList<String>> hashMap3 = new HashMap<>();
        hashMap.put("com.taobao.android.detail2.core.framework.NewDetailActivity", hashMap3);
        ArrayList<String> arrayList2 = new ArrayList<>();
        arrayList2.add("taobao_favorite_aar");
        arrayList2.add("ratefeature");
        arrayList2.add("fliggy_vacation_detail");
        hashMap3.put("default", arrayList2);
        HashMap<String, ArrayList<String>> hashMap4 = new HashMap<>();
        hashMap.put("com.taobao.android.detail.wrapper.activity.DetailActivity", hashMap4);
        ArrayList<String> arrayList3 = new ArrayList<>();
        arrayList3.add("taobao_favorite_aar");
        arrayList3.add("ratefeature");
        arrayList3.add("fliggy_vacation_detail");
        hashMap4.put("default", arrayList3);
        HashMap<String, ArrayList<String>> hashMap5 = new HashMap<>();
        hashMap.put("com.taobao.search.sf.MainSearchResultActivity", hashMap5);
        ArrayList<String> arrayList4 = new ArrayList<>();
        arrayList4.add("tbsearch_remote");
        arrayList4.add("taowise_android_aar");
        arrayList4.add("voice_assistant");
        hashMap5.put("default", arrayList4);
        HashMap<String, ArrayList<String>> hashMap6 = new HashMap<>();
        hashMap.put("com.taobao.android.order.bundle.TBOrderListActivity", hashMap6);
        ArrayList<String> arrayList5 = new ArrayList<>();
        arrayList5.add(u58.DYNAMIC_NAME_TAOBAO_ANDROID_AMAP_DYNAMIC);
        hashMap6.put("default", arrayList5);
        HashMap<String, ArrayList<String>> hashMap7 = new HashMap<>();
        hashMap.put(FlexaLiveX.TAO_LIVE_VIDEO_ACTIVITY, hashMap7);
        ArrayList<String> arrayList6 = new ArrayList<>();
        arrayList6.add(FlexaLiveX.TBLIVE_GIFT);
        arrayList6.add(FlexaLiveX.TAOLIVE_HOMEPAGE);
        arrayList6.add(FlexaLiveX.ATYPE);
        arrayList6.add(FlexaLiveX.BTYPE);
        arrayList6.add(tbt.MORE_FEATURE);
        hashMap7.put("default", arrayList6);
        HashMap<String, ArrayList<String>> hashMap8 = new HashMap<>();
        hashMap.put(FlexaLiveX.TAO_LIVE_HOME_ACTIVITY, hashMap8);
        ArrayList<String> arrayList7 = new ArrayList<>();
        arrayList7.add(FlexaLiveX.TBLIVE_GIFT);
        arrayList7.add(FlexaLiveX.TAOLIVE_HOMEPAGE);
        arrayList7.add(FlexaLiveX.ATYPE);
        arrayList7.add(FlexaLiveX.BTYPE);
        arrayList7.add(tbt.MORE_FEATURE);
        hashMap8.put("default", arrayList7);
        HashMap<String, ArrayList<String>> hashMap9 = new HashMap<>();
        hashMap.put(obq.BIZ_NAME, hashMap9);
        ArrayList<String> arrayList8 = new ArrayList<>();
        arrayList8.add("taobao_favorite_aar");
        arrayList8.add(u58.DYNAMIC_NAME_TAOBAO_ANDROID_AMAP_DYNAMIC);
        hashMap9.put("mytaobao", arrayList8);
        ArrayList<String> arrayList9 = new ArrayList<>();
        arrayList9.add(a.TAOPAI_FEATURE);
        arrayList9.add("litecreator");
        arrayList9.add(a.TAOPAI_SDK_FEATURE);
        arrayList9.add("rxandroid");
        arrayList9.add("ratefeature");
        arrayList9.add("tbvsvideofeature");
        arrayList9.add("tbsocialsdk");
        arrayList9.add("layoutmanager_feature");
        arrayList9.add("umipublish");
        arrayList9.add("fluid_remote");
        hashMap9.put("tab2", arrayList9);
        ArrayList<String> arrayList10 = new ArrayList<>();
        arrayList10.add(a.TAOPAI_SDK_FEATURE);
        arrayList10.add("rxandroid");
        arrayList10.add("taobao_wangxin");
        arrayList10.add("messagesdkwrapper");
        hashMap9.put("message", arrayList10);
        ArrayList<String> arrayList11 = new ArrayList<>();
        arrayList11.add("order_remote");
        arrayList11.add("taobao_wangxin");
        arrayList11.add(u58.DYNAMIC_NAME_TAOBAO_ANDROID_AMAP_DYNAMIC);
        arrayList11.add("taobao_shake_sdk");
        arrayList11.add("taobao_weex_adapter");
        arrayList11.add("taobao_favorite_aar");
        arrayList11.add("voice_assistant");
        arrayList11.add("TBSubscribe");
        arrayList11.add("left_sdk");
        arrayList11.add("elemeadapter_android");
        hashMap9.put("homePage", arrayList11);
        HashMap<String, ArrayList<String>> hashMap10 = new HashMap<>();
        hashMap.put("com.alibaba.triver.container.TriverMainActivity", hashMap10);
        ArrayList<String> arrayList12 = new ArrayList<>();
        arrayList12.add("triver_taobao");
        hashMap10.put("default", arrayList12);
        return hashMap;
    }
}
