package tb;

import com.android.alibaba.ip.runtime.IpChange;
import com.taobao.taobaoavsdk.Tracer.BaseAnalysis;
import java.util.HashMap;
import java.util.Map;

/* compiled from: Taobao */
/* loaded from: /Users/corson/Downloads/taobao_decompiled/build/apk/classes8.dex */
public class r7t {
    public static volatile transient /* synthetic */ IpChange $ipChange = null;
    public static final int DECODER_TYPE_HARDWARE = 1;
    public static final int DECODER_TYPE_SOFTWARE = 0;
    public static final int PLAYER_TYPE_FF = 1;
    public static final int PLAYER_TYPE_MEDIA = 2;
    public static final int PLAYER_TYPE_TAOBAO = 3;
    public static final int RENDER_TYPE_SURFACE_VIEW = 1;
    public static final int RENDER_TYPE_TEXTURE_VIEW = 2;
    public static final int RENDER_TYPE_VR_VIEW = 3;
    public static final int SCALE_TYPE_CENTER_CROP = 1;
    public static final int SCALE_TYPE_FIT_CENTER = 0;
    public static final int SCALE_TYPE_FIT_XY = 3;
    public static final int SCENARIO_TYPE_LINKLIVE = 1;
    public static final int SCENARIO_TYPE_LIVE = 0;
    public static final int SCENARIO_TYPE_PLAYBACK = 2;
    public static final int VR_RENDER_TYPE_180_LEFT_RIGHT = 3;
    public static final int VR_RENDER_TYPE_180_UP_DOWN = 2;
    public static final int VR_RENDER_TYPE_360_EQUIRECTANGULAR = 1;
    public static final int mDisableH26XByBlackList = 1;
    public static final int mDisableH26XByBusinessSet = 3;
    public static final int mDisableH26XByHWFailed = 4;
    public static final int mDisableH26XByInit = 0;
    public static final int mDisableH26XByTag = 5;
    public static final int mDisableH26XSetByConfig = 2;
    public String A;
    public String B;
    public String C;
    public String D;
    public String E;
    public boolean E0;
    public String F;
    public boolean F0;
    public String G;
    public String H;
    public int I;
    public String J;
    public boolean K0;
    public String L;
    public boolean L0;
    public boolean M;
    public boolean M0;
    public String N;
    public boolean N0;
    public boolean O;
    public boolean O0;
    public String P;
    public boolean P0;
    public String Q;
    public boolean Q0;
    public boolean S;
    public Map<String, String> U;
    public BaseAnalysis U0;
    public int g;
    public int h;
    public int i;
    public int i0;
    public String k0;
    public boolean l0;
    public String m0;
    public String n0;
    public boolean o;
    public String o0;
    public String p;
    public long p0;
    public String q;
    public boolean q0;
    public String r;
    public String r0;
    public String s;
    public String t;
    public int u;
    public String u0;
    public String v;
    public String w;
    public boolean w0;
    public String x;
    public int x0;
    public String y;
    public boolean y0;
    public String z;

    /* renamed from: a  reason: collision with root package name */
    public int f27172a = -1;
    public boolean b = false;
    public int c = 1;
    public int d = 0;
    public int e = 2;
    public int f = 1;
    public int j = 1;
    public int k = -1;
    public int l = -1;
    public boolean m = true;
    public boolean n = true;
    public int K = -1;
    public boolean R = false;
    public int W = 0;
    public int X = 0;
    public int Y = 0;
    public boolean Z = false;
    public boolean a0 = false;
    public boolean b0 = true;
    public int c0 = 0;
    public boolean d0 = false;
    public boolean e0 = false;
    public int f0 = 1;
    public int g0 = 0;
    public boolean h0 = false;
    public boolean j0 = false;
    public int s0 = 0;
    public long t0 = -1;
    public boolean v0 = true;
    public int z0 = 0;
    public boolean A0 = false;
    public boolean B0 = false;
    public boolean C0 = false;
    public boolean D0 = false;
    public int G0 = 0;
    public int H0 = 0;
    public int I0 = -1;
    public int J0 = -1;
    public int R0 = 0;
    public boolean S0 = false;
    public boolean T0 = false;
    public boolean V0 = false;
    public boolean W0 = false;
    public boolean X0 = false;
    public boolean Y0 = false;
    public Map<String, String> T = new HashMap();
    public Map<String, String> V = new HashMap();

    static {
        t2o.a(774897989);
    }

    public r7t() {
        this.g = 0;
        this.h = 0;
        this.g = 1;
        this.h = 1;
    }

    /* renamed from: a */
    public r7t clone() {
        IpChange ipChange = $ipChange;
        if (ipChange instanceof IpChange) {
            return (r7t) ipChange.ipc$dispatch("1a2beb82", new Object[]{this});
        }
        r7t r7tVar = new r7t(this.x);
        r7tVar.C = this.C;
        r7tVar.m = this.m;
        r7tVar.o = this.o;
        r7tVar.n = this.n;
        r7tVar.r = this.r;
        r7tVar.q = this.q;
        r7tVar.i = this.i;
        r7tVar.g = this.g;
        r7tVar.h = this.h;
        r7tVar.H = this.H;
        r7tVar.L = this.L;
        r7tVar.B = this.B;
        r7tVar.F = this.F;
        r7tVar.K = this.K;
        r7tVar.c = this.c;
        r7tVar.t = this.t;
        r7tVar.e = this.e;
        r7tVar.f = this.f;
        r7tVar.d = this.d;
        r7tVar.G = this.G;
        r7tVar.y = this.y;
        r7tVar.p = this.p;
        r7tVar.A = this.A;
        r7tVar.z = this.z;
        r7tVar.D = this.D;
        r7tVar.E = this.E;
        r7tVar.u = this.u;
        r7tVar.v = this.v;
        r7tVar.w = this.w;
        r7tVar.l = this.l;
        r7tVar.k = this.k;
        r7tVar.j = this.j;
        r7tVar.s = this.s;
        r7tVar.M = this.M;
        r7tVar.N = this.N;
        r7tVar.O = this.O;
        r7tVar.P = this.P;
        r7tVar.Q = this.Q;
        r7tVar.R = this.R;
        r7tVar.S = this.S;
        r7tVar.T = this.T;
        r7tVar.V = this.V;
        r7tVar.U = this.U;
        r7tVar.Z = this.Z;
        r7tVar.a0 = this.a0;
        r7tVar.c0 = this.c0;
        r7tVar.d0 = this.d0;
        r7tVar.e0 = this.e0;
        r7tVar.f0 = this.f0;
        r7tVar.i0 = this.i0;
        r7tVar.j0 = this.j0;
        r7tVar.k0 = this.k0;
        r7tVar.l0 = this.l0;
        r7tVar.m0 = this.m0;
        r7tVar.n0 = this.n0;
        r7tVar.o0 = this.o0;
        r7tVar.p0 = this.p0;
        r7tVar.q0 = this.q0;
        r7tVar.r0 = this.r0;
        r7tVar.w0 = this.w0;
        r7tVar.x0 = this.x0;
        r7tVar.y0 = this.y0;
        r7tVar.F0 = this.F0;
        r7tVar.b0 = this.b0;
        r7tVar.z0 = this.z0;
        r7tVar.E0 = this.E0;
        r7tVar.G0 = this.G0;
        r7tVar.H0 = this.H0;
        r7tVar.s0 = this.s0;
        r7tVar.A0 = this.A0;
        r7tVar.B0 = this.B0;
        r7tVar.C0 = this.C0;
        r7tVar.D0 = this.D0;
        r7tVar.t0 = this.t0;
        r7tVar.u0 = this.u0;
        r7tVar.v0 = this.v0;
        r7tVar.I0 = this.I0;
        r7tVar.J0 = this.J0;
        r7tVar.K0 = this.K0;
        r7tVar.L0 = this.L0;
        r7tVar.M0 = this.M0;
        r7tVar.N0 = this.N0;
        r7tVar.O0 = this.O0;
        r7tVar.R0 = this.R0;
        r7tVar.f27172a = this.f27172a;
        r7tVar.P0 = this.P0;
        r7tVar.Q0 = this.Q0;
        r7tVar.S0 = this.S0;
        r7tVar.T0 = this.T0;
        r7tVar.V0 = this.V0;
        r7tVar.W0 = this.W0;
        r7tVar.X0 = this.X0;
        r7tVar.Y0 = this.Y0;
        return r7tVar;
    }

    public r7t(String str) {
        this.g = 0;
        this.h = 0;
        this.x = str;
        this.g = 1;
        this.h = 1;
    }
}
